name = "Liva Liva"
license = ""
licenselink = ""
description = "Port of the Themefisher’s Liva Template by Datasciencia.com"
homepage = "https://gethugothemes.com/products/liva-hugo/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.1"

[author]
  name = "datasciencia.com"
  homepage = "https://datasciencia.com/"
